### ISSUE TITLE
Show a big warning that they aren't in the student list if email not found.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#10]
Instruct students to logout and be sure to log back in with a valid mica email or contact someone about getting on the list

**Comment by webmasterkai** [comment]
showing warning if non mica email. still no whitelist

**Comment by webmasterkai** [comment]
Edit warming message for no student info here https://console.firebase.google.com/project/mica2017-18d52/database/data/db/authStudentMissing
