### ISSUE TITLE
How to handle hours for the galleries

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#14]
Some galleries have the same hours every day, others have different times and days, where to collect/feed this data from

**Comment by webmasterkai** [comment]
Airtable doesn't have a way for entering in this information. As-is it's just going to spit out as a text string. Maybe that's ok.

**Comment by bjornmeansbear** [comment]
As long as we have the hours in a legible way on the detailed showGroup page, it can be a string or whatever is easiest.

**Comment by bjornmeansbear** [comment]
The text string as it is will be fine!

**Comment by bjornmeansbear** [comment]
closed by acd12708f66c1374de5a4a91e71154203172c47b
