### ISSUE TITLE
Filter student list by program

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#20]
In the past we've been able to chunk people by their program. This can be done on the student list by either letting the search bar also search programs, not just the names, or we could have some button/dropdown that did programs

**Comment by webmasterkai** [comment]
dropdown or multi-select?

**Comment by bjornmeansbear** [comment]
do you have a preference? you seemed to think that buttons or something else would have been good for DL's view controls. I'm fine and will make look good whatever preference you have — is one easier than another?

**Comment by webmasterkai** [comment]
most basic filter done
