### ISSUE TITLE
Detail page can start pulling in content

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#39]
I think we have enough to get started!

**Comment by bjornmeansbear** [comment]
I've been exploring this, but I've not really figured out how I can make this work on my own yet.

**Comment by webmasterkai** [comment]
Is this done?

**Comment by bjornmeansbear** [comment]
List of locations to show under `location` header

And then I guess trying to get the map to work? where the galleries/locations for that showGroup are presented

**Comment by bjornmeansbear** [comment]
I can make new issues...
 cause there needs to be a solution for students not in the "all in" category for gallery/location placement
