### ISSUE TITLE
Multiple opening receptions for Show III

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#43]
On campus galleries have their opening on Friday, 4/21 — off campus galleries have their opening on 4/22 (7pm-10pm)

**Comment by bjornmeansbear** [comment]
related to #45

**Comment by webmasterkai** [comment]
This would need to be split into two ShowGroups in airtable and then combined or not when necessary on the website.

**Comment by bjornmeansbear** [comment]
Okay. So if I make them in Airtable, we can then discuss how to combine them where necessary?

**Comment by webmasterkai** [comment]
I think that's best. Sounds like another ShowGroup would solve this splitting of locations and reception dates.

**Comment by webmasterkai** [comment]
You could even give them both the same `name` value in airtable if needed.

**Comment by bjornmeansbear** [comment]
Okay, `Show III` has two receptions, at two different places. `Filmmaking MFA Screenings` has two receptions, but at the same place, just on the two different nights. And — `Common Senses` has two as well different locations AND different running dates for the show as a whole…

This is supposed to get easier each year... 💥 

I updated the olds and added the new ones in AirTable

**Comment by bjornmeansbear** [comment]
Is something like this too complicated?
![screenshot 2017-02-06 12 10 25](https://cloud.githubusercontent.com/assets/324987/22657710/6c3d8b2c-ec65-11e6-9405-0a7bceb891c8.png)

Just printing reception/location pairings twice?
Otherwise the Title, showDates, description and full student/show pairings would be there together

**Comment by bjornmeansbear** [comment]
Feck, but that doesn't quite work for CommonSense #45 which has multiple dates also...

**Comment by webmasterkai** [comment]
Did you decide how this should work?

**Comment by bjornmeansbear** [comment]
I at least have something to talk about... let me know when we can do that, you can throw in your 2 cents and tell me I'm crazy

**Comment by webmasterkai** [comment]
Pull the "child" (recL5bU5855qMhQT4 ) entity out of the database and add it to the "parent" (recy5OLOvJNnpWuAD) within the client code. Perhaps put the reception/location groupings together on a field and map on that field to create the two inner components? We agreed to try to print the student list just after each location.
