### ISSUE TITLE
Is it worth individually placing students for Show3 on the website proper?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#48]
Is there a clever way to link individual students to a specific gallery? maybe not w/ the new setup?

related to #44

**Comment by webmasterkai** [comment]
Why a gallery and not a show?

**Comment by bjornmeansbear** [comment]
Yeah, the shows are our thing, but what's important for the Grad people is that it is the galleries, so I just didn't phrase it correctly. I can pick them on a per show basis now. Coolio!
