### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#5]
- ask students for their Facebook profile name
- ask students for their instagram id
- ask students for twitter handle
- make sure validating helps them to find just the id, name, etc., not an entire URL?

**Comment by webmasterkai** [comment]
I vote for making validating a new issue since that's a rather large task.

**Comment by bjornmeansbear** [comment]
Validating is a new issue, great. I'll try to get better at thinking of these things in their little parts and making issues that way. 💥
