### ISSUE TITLE
Show column on studentsList should list their ShowGroup if possible? not just show

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#52]

**Comment by bjornmeansbear** [comment]
Since we label everything by showGroup on the schedule, we need those to match so people can make sense of this.

**Comment by bjornmeansbear** [comment]
![screenshot 2017-01-19 15 21 39](https://cloud.githubusercontent.com/assets/324987/22123828/3c2b62dc-de5b-11e6-9dea-0a660ea17136.png)

So, This would say `Show II` instead of `graphic Riggs`, `pb camp` and `Show I` instead of `teach Riggs` for examples

**Comment by webmasterkai** [comment]
Where is this?

**Comment by bjornmeansbear** [comment]
this is on the student page.
