### ISSUE TITLE
Two conflicting Studio Art names

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#56]
M.F.A Studio Art and Studio Art MFA

Studio Art MFA is the desired title as it matches everything else.

I don't know where M.F.A. Studio Art came from?

**Comment by bjornmeansbear** [comment]
There is one program showing up just as `mfastudio` in Firebase

But the one from Airtable, that has the correct Name and the shows/showgroup attached to it is `recunk9dSiB9V7CKE` in firebase...

Perhaps the `mfastudio` one came from the MICA url? or did something else happen?

**Comment by webmasterkai** [comment]
Incorrectt alias in airtable. I added `mfastudio`.

**Comment by webmasterkai** [comment]
bob's your auntie
