### ISSUE TITLE
URL field

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#6]
- students should be able to add the url to their portfolio or project's website
- should we allow multiple websites???

**Comment by webmasterkai** [comment]
I'll have to dig up that fancy website field thingy that got all kinds of extra info.

**Comment by bjornmeansbear** [comment]
Oh, where it found the site name, and an image, etc?
And it created a unique ID# for the thing?
What if we just start out with the simple version?

**Comment by webmasterkai** [comment]
Added a singular URL field. Defined in `/components/Profile/personFields.js`.

**Comment by bjornmeansbear** [comment]
bam! simple version done!
