### ISSUE TITLE
Detail Page: How to handle printing student names from programs not "all in" a location?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#61]
there needs to be a solution for students not in the "all in" category for gallery/location placement

**Comment by webmasterkai** [comment]
I'm going to start with creating a page that has a list of students that are not in one of the `allStudentsIn` programs.

**Comment by bjornmeansbear** [comment]
sounds like a good place to start

**Comment by webmasterkai** [comment]
Only display shows that match student program.

**Comment by webmasterkai** [comment]
The edits will be blown away when we update from airtable. Still need to fix that. Otherwise should be working as expected.

**Comment by bjornmeansbear** [comment]
Great! I am seeing everyone. So that's fantastic.
