### ISSUE TITLE
Some ShowGroups maps need a different center lat/lng on Detail map

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#62]
I can do a lat/lng for show groups w/ different centering needs in airtable, but I think the lat/lng values for centering the google map are desired in an object it looks like, not just individual strings...

a custom zoom for some of the maps might be necessary 

examples: like ShowIII might need to zoom out 1 level and move the center, Creative Alchemy is in DC, so its center needs to move the map there instead of hovering over MICA...

**Comment by bjornmeansbear** [comment]
I can just add them to firebase directly, but will that get removed when/if updates from airtable are made again?

**Comment by bjornmeansbear** [comment]
Figured out on the components themselves how to do this. Manually added two examples for now in firebase so I could test things. a730fde95e974778d0da79f6b5197b6e216e78e9

**Comment by webmasterkai** [comment]
Add the lat lng to airtable on showgroup is probably the best way

**Comment by bjornmeansbear** [comment]
k cool

**Comment by bjornmeansbear** [comment]
I'll try to get these sorted tonight.

**Comment by bjornmeansbear** [comment]
The one's I'm sure about are added/updated in airtable. Firebase DB can be updated
