### ISSUE TITLE
FilmFest schedule is really complicated. Is there a way to link to a unique page just for the filmfest shcedule?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#66]
I've made a rough schedule page just for the film screenings, that might be an easier way of handling it than trying to make each film its own show with multiple days and times fitting into the larger showGroup also with multiple days and receptions?

**Comment by webmasterkai** [comment]
If it's easy to make a new table that'd be cool. Otherwise we can hard code it

**Comment by webmasterkai** [comment]
Will a new sheet work or should it just be custom?

**Comment by bjornmeansbear** [comment]
I made a component that just has the content.

`/components/FilmFest/`

It seemed hard to standardize data entry wise?
