### ISSUE TITLE
Email field.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#8]
- accepts only mica.edu emails
- only emails on list provided by TSS can “login” «— still need this from Evan 
- Auth against their mica google acts

**Comment by webmasterkai** [comment]
(1) I think it will auth with google first and then if they aren't found we'll show a big warning that they aren't in the student list. They should logout and log back in with a valid mica email or contact someone about getting on the list.

(2) We can then add field that validates the email against the database like before and then sends the suggestion to google about what email they should login with.

**Comment by bjornmeansbear** [comment]
Awesome. So should I break this into smaller issues addressing those concerns separately?

**Comment by bjornmeansbear** [comment]
replaced by #10, #11, and #12
